### ISSUE TITLE
Create a guide and docker container for running a public API node

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#27] opened 2019-10-16 01:45 UTC
@gz-c commented on Jun 2

_No description provided._

**Comment by vidya88** [comment] 2019-10-16 01:47
@gz-c commented on Jul 10

Related to or duplicate of [#2361](https://github.com/skycoin/skycoin/issues/2361)

**Comment by BigOokie** [comment] 2019-10-16 19:55
You will want to take into consideration #31 to ensure the node can be run using HTTPS

**Comment by iketheadore** [comment] 2019-11-24 14:20
Duplicate of #31

**Closed by iketheadore** 2019-11-24 14:20 UTC
Labels: docs
